### PR TITLE
Refactored the code using proper refactoring techniques.

### PR DESCRIPTION
**Pull request by janvipatel23**

### CODE REVIEW

**Comment by janvipatel23** [comment]
The existing code quality has been improved by applying the following refactoring techniques concepts:
1. Rename Variable
2. Extract Method
3. Pull-up Method
4. Extract Class
5. Move Method

Additionally, resolved one of the build error bugs by removing the duplication of the code from the DirectMessage.java file.

For the test cases, some of the existing test cases were already failing before refactoring change due to using Apis which is being deprecated by Twitter now. Hence, disabled those test cases.

Please have a look at the commit and accept the pull request.

**Comment by yusuke** [comment]
Thanks for the pull request.
Please avoid renaming public interfaces / classes as it'll break backward compatibilities.

**Comment by janvipatel23** [comment]
Okay sure will do that and push the code again.

**Comment by janvipatel23** [comment]
I have reverted the changes that you mentioned. Please have a look.

**Comment by janvipatel23** [comment]
Hello,
Can you please approve the pull request? I reverted back the changes you
suggested. Please accept the pull request by 25 March 11:59 pm AST. As I
have deadline of assignment tomorrow.
It’s okay if u don’t merge it. It would be great help from yourside to gain
me some bonus points.
Hope to hear from you soon!
Thanks & Regards,
Janvi

**Pull request closed without merging**
