### PR TITLE
change package structure so twitter4j can be used in JDK9 modules

### PR DESCRIPTION
**Pull request by SingingBush**
The current versions of twitter4j cannot be used in Java 9 modules due to split packages. Java 9 module allows for "automatic modules" where if the dependency was not a modular build it can still be used as a module based on jar file name, so `twitter4j-core-4.0.6.jar` becomes `twitter4j.core`. Unfortunately as so much of the source code is in a single package `twitter4j` there is a problem. Java 9 modules do not allow split packages (where multiple modules have the same package). so it's not possible to require both `twitter4j.core` and `twitter4j.stream`. 

I've resolved this be restructuring the project so that all classes are in packages in the format org.twitter4j.packagename, eg: (_org.twitter4j.core_, _org.twitter4j.stream_).

I also set the minimum Java version as JDK 8 and set the project version as 5.0.0-SNAPSHOT

### CODE REVIEW

**Comment by SingingBush** [comment]
Travis build will now pass (the JDK9 one just failed due to problem retrieving the jdk - normally fine)
travis

**Comment by twasyl** [comment]
It would be awesome if this PR could be merged as I'm also waiting for it.

**Comment by michaelsavich** [comment]
Yeah, this PR looks cool. Any reason it hasn't been merged yet?

**Comment by SingingBush** [comment]
I doubt this will get merged, the project hasn't had a commit all year and there have been numerous other pull requests. I did the minimum required to get it working for a Java9 demo I was working on.
You may be best off checking out the branch and doing a mvn install locally on your machine so that you can use it.

**Comment by eos1d3** [comment]
Look like this is dying. Lack of video upload for two years is hard to believe. 
@yusuke Would you please tell us the current situation of this project?

**Comment by michaelsavich** [comment]
Well, after examining the project I found that twitter4j's logging utilities have some pretty nasty dependencies that would keep twitter4j from running on smaller jlink'd JREs (somehow even java.desktop is required…).

I'm in the process of ripping out the logging functionality. I'm not sure whether I will to try pull-request this in when it's done, because it's kind of a chainsaw hack job right now, but I'll burn that bridge when I come to it.

**Comment by yusuke** [comment]
Twitter4J is now module aware. thanks!

**Comment by SingingBush** [comment]
@yusuke thanks. looking forward to trying the next release

**Pull request closed without merging**
